package models

type GuestType string

const (
	GuestTypeCT GuestType = "ct"
	GuestTypeVM GuestType = "vm"
)

type Status string

const (
	StatusRunning Status = "running"
	StatusStopped Status = "stopped"
)

// ConsoleTransport selects how a guest CONSOLE is attached.
//
// It says nothing about whether proxpass can reach the Proxmox node, and
// nothing about file transfer. It used to: only the ssh value populated the
// instance's SSH fields, so choosing the websocket transport silently meant
// "this node is unreachable", and transfers were refused on instances whose
// node answers SSH perfectly well. The two are independent -- how a terminal
// is attached is unrelated to whether sshd is listening -- so the SSH fields
// are now filled in either way and this selects only the console.
type ConsoleTransport string

const (
	// ConsoleTransportTermProxy attaches the terminal through the Proxmox
	// REST API's termproxy endpoint over a WebSocket. It is the default,
	// and needs no SSH access for the console itself.
	ConsoleTransportTermProxy ConsoleTransport = "termproxy"

	// ConsoleTransportSSH attaches the terminal by running pct enter or qm
	// terminal over SSH on the node.
	ConsoleTransportSSH ConsoleTransport = "ssh"
)

type ProxmoxInstance struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	APIURL         string `json:"api_url"`
	APITokenID     string `json:"api_token_id"`
	APITokenSecret string `json:"api_token_secret"`
	// ConsoleTransport selects how a console is attached; see the type. It
	// does NOT decide whether the SSH fields below are set.
	ConsoleTransport ConsoleTransport `json:"console_transport"`
	Node             string           `json:"node"` // resolved Proxmox short node name

	// How to reach the Proxmox NODE over SSH. Populated for every instance,
	// whatever the console transport: the node is the same machine either
	// way, and file transfer runs commands there regardless of how consoles
	// are attached. Whether proxpass may actually log in is decided by the
	// key, not by these.
	SSHHost string `json:"ssh_host"`
	SSHPort int    `json:"ssh_port"`
	SSHUser string `json:"ssh_user"`

	// There is deliberately no key here. proxpass owns ONE key for the whole
	// deployment, generated by the entrypoint on the volume and named by
	// PROXPASS_SSH_KEY_FILE -- see DefaultSSHKeyPath. Storing a key per
	// instance meant the database held Proxmox credentials, and installing
	// its public half on each host by hand bought no isolation, since
	// whoever could read one row could read them all.
}

type Guest struct {
	ID         int64     `json:"id"`
	Type       GuestType `json:"type"`
	Name       string    `json:"name"`
	Status     Status    `json:"status"`
	ProxmoxID  int       `json:"proxmox_id"`
	InstanceID int64     `json:"instance_id"`
}

type Client struct {
	ID         int64    `json:"id"`
	Name       string   `json:"name"`
	PublicKeys []string `json:"public_keys"`
	GroupIDs   []int64  `json:"group_ids"`
}

type Group struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	ClientIDs []int64 `json:"client_ids"`
}

type RuleType string

const (
	RuleClient RuleType = "client"
	RuleGroup  RuleType = "group"
)

// AccessRuleRow is a flat per-row representation of an access rule (one guest per row).
type AccessRuleRow struct {
	ID        int64    `json:"id"`
	Type      RuleType `json:"type"`
	SubjectID int64    `json:"subject_id"`
	GuestID   int64    `json:"guest_id"`
}

type DefaultAccessPolicy struct {
	AuthorizedClientIDs []int64 `json:"authorized_client_ids"`
	AuthorizedGroupIDs  []int64 `json:"authorized_group_ids"`
}

// SessionIdentity is who a session turned out to be, as resolved from the
// key that authenticated it.
//
// It is stored against a bearer token at authentication time and handed back
// when that token is redeemed, so that `proxpass serve' can answer "who are
// you" without the session having to claim anything. The session's own view
// of this lives in internal/session.Identity; this is the part that has to
// survive in the database between the two processes.
//
// ClientID is 0 for the administrator, who has no client row.
type SessionIdentity struct {
	// LoginName is what the caller typed in `ssh <name>@host'.
	//
	// It is a REQUEST PARAMETER, not an identity. Any name the directory
	// does not already serve resolves to an alias, so anybody can pick
	// anybody else's -- which is why the session also accepts it as a
	// guest target ("ssh ct100@host"). Never log it as the actor and never
	// make an authorization decision from it: use IdentityName and the
	// IsAdmin/ClientID fields instead.
	LoginName string `json:"login_name"`

	// IdentityName is WHO THE CALLER IS: the clients.name row the
	// authenticating key belongs to, or the administrator's name.
	//
	// Resolved by `proxpass authorized-keys', which runs as root before the
	// session exists and therefore knows which key is which. The session
	// cannot influence it. This is the name to log, the name to show, and
	// the name an operator will grep for.
	//
	// It is deliberately not called IdentityName any more: that invited
	// treating it as a cosmetic string safe to truncate or localize, which
	// would quietly corrupt the audit trail.
	IdentityName string `json:"identity_name"`

	IsAdmin  bool  `json:"is_admin"`
	ClientID int64 `json:"client_id"`
}
