//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GuestStatus.
const (
	Running GuestStatus = "running"
	Stopped GuestStatus = "stopped"
)

// Valid indicates whether the value is a known member of the GuestStatus enum.
func (e GuestStatus) Valid() bool {
	switch e {
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for GuestType.
const (
	Ct GuestType = "ct"
	VM GuestType = "vm"
)

// Valid indicates whether the value is a known member of the GuestType enum.
func (e GuestType) Valid() bool {
	switch e {
	case Ct:
		return true
	case VM:
		return true
	default:
		return false
	}
}

// Defines values for InstanceCredentialsConnectionType.
const (
	SSH       InstanceCredentialsConnectionType = "ssh"
	Termproxy InstanceCredentialsConnectionType = "termproxy"
)

// Valid indicates whether the value is a known member of the InstanceCredentialsConnectionType enum.
func (e InstanceCredentialsConnectionType) Valid() bool {
	switch e {
	case SSH:
		return true
	case Termproxy:
		return true
	default:
		return false
	}
}

// ConnectInfo Everything needed to open one guest's console, and nothing about any
// other guest or instance.
type ConnectInfo struct {
	// Guest A guest as a picker needs it. Deliberately carries nothing that could
	// be used to reach the guest: a session holds this list for its whole
	// life, and most of it is never connected to.
	Guest Guest `json:"guest"`

	// Instance The Proxmox credentials for the instance hosting one guest.
	//
	// This is the material a session must not be able to read from the
	// database, handed over for a single connection it has been authorized
	// to make.
	Instance InstanceCredentials `json:"instance"`
}

// Error defines model for Error.
type Error struct {
	// Error A short reason. Deliberately not detailed: these responses are
	// reachable before a caller is authenticated.
	Error string `json:"error"`
}

// Guest A guest as a picker needs it. Deliberately carries nothing that could
// be used to reach the guest: a session holds this list for its whole
// life, and most of it is never connected to.
type Guest struct {
	// ID The row id, used to ask for a connection.
	ID         int64 `json:"id"`
	InstanceID int64 `json:"instanceId"`

	// InstanceName Included so a caller can show and match on it without a second
	// request. It is the only thing about an instance a picker needs,
	// which is why there is no endpoint that lists instances.
	InstanceName string `json:"instanceName"`
	Name         string `json:"name"`

	// ProxmoxID The guest's id within its Proxmox instance, e.g. 100.
	ProxmoxID int         `json:"proxmoxId"`
	Status    GuestStatus `json:"status"`
	Type      GuestType   `json:"type"`
}

// GuestStatus defines model for Guest.Status.
type GuestStatus string

// GuestType defines model for Guest.Type.
type GuestType string

// Identity Who a session is, as resolved from its token.
type Identity struct {
	// ClientID The client's row id. Absent for the administrator.
	ClientID *int64 `json:"clientId,omitempty"`

	// DisplayName The configured identity to show the user: the admin user name, or
	// the client's own name. The login name is an alias the caller
	// chose, so it is not what the UI should display.
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`

	// User The login name the session arrived with, kept for the audit log.
	User string `json:"user"`
}

// InstanceCredentials The Proxmox credentials for the instance hosting one guest.
//
// This is the material a session must not be able to read from the
// database, handed over for a single connection it has been authorized
// to make.
type InstanceCredentials struct {
	APITokenID *string `json:"apiTokenId,omitempty"`

	// APITokenSecret Present when the instance connects over the API.
	APITokenSecret *string                           `json:"apiTokenSecret,omitempty"`
	APIURL         string                            `json:"apiUrl"`
	ConnectionType InstanceCredentialsConnectionType `json:"connectionType"`
	ID             int64                             `json:"id"`
	Name           string                            `json:"name"`

	// Node The resolved Proxmox short node name.
	Node    string  `json:"node"`
	SSHHost *string `json:"sshHost,omitempty"`

	// SSHKey PEM-encoded private key, inline. An instance configured with a
	// key PATH is resolved here by reading the file, because the
	// session cannot: the key is deliberately outside its reach.
	SSHKey  *string `json:"sshKey,omitempty"`
	SSHPort *int    `json:"sshPort,omitempty"`
	SSHUser *string `json:"sshUser,omitempty"`
}

// InstanceCredentialsConnectionType defines model for InstanceCredentials.ConnectionType.
type InstanceCredentialsConnectionType string

// SessionCredential A session credential and the identity it speaks for.
type SessionCredential struct {
	// ExpiresAt When it stops working regardless of use. A session outliving this
	// has to exchange again, which it cannot do -- so the window is
	// generous enough to cover a long console attach.
	ExpiresAt time.Time `json:"expiresAt"`

	// Identity Who a session is, as resolved from its token.
	Identity Identity `json:"identity"`

	// Token Present this as the bearer token on later calls. Hold it in
	// memory only: putting it in the environment would undo the reason
	// it exists.
	Token string `json:"token"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// IsLoginNameReservedParams defines parameters for IsLoginNameReserved.
type IsLoginNameReservedParams struct {
	Name string `form:"name" json:"name"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(w http.ResponseWriter, r *http.Request)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(w http.ResponseWriter, r *http.Request)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(w http.ResponseWriter, r *http.Request)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(w http.ResponseWriter, r *http.Request)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectSessionGuest operation middleware
func (siw *ServerInterfaceWrapper) ConnectSessionGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guestId" -------------
	var guestID int64

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", r.PathValue("guestId"), &guestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectSessionGuest(w, r, guestID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeSessionToken operation middleware
func (siw *ServerInterfaceWrapper) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeSessionToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessionGuests operation middleware
func (siw *ServerInterfaceWrapper) ListSessionGuests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessionGuests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IsLoginNameReserved operation middleware
func (siw *ServerInterfaceWrapper) IsLoginNameReserved(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IsLoginNameReservedParams

	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IsLoginNameReserved(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicEndpoint(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSessionCredential operation middleware
func (siw *ServerInterfaceWrapper) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSessionCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/exchange", wrapper.ExchangeSessionToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/revoke", wrapper.RevokeSessionCredential)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/guests", wrapper.ListSessionGuests)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/connect/{guestId}", wrapper.ConnectSessionGuest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/login-name-reserved", wrapper.IsLoginNameReserved)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/public-endpoint", wrapper.GetPublicEndpoint)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/identity", wrapper.GetSessionIdentity)

	return m
}

type UnauthorizedJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type ConnectSessionGuestRequestObject struct {
	GuestID int64 `json:"guestId"`
}

type ConnectSessionGuestResponseObject interface {
	VisitConnectSessionGuestResponse(w http.ResponseWriter) error
}

type ConnectSessionGuest200JSONResponse ConnectInfo

func (response ConnectSessionGuest200JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ConnectSessionGuest401JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest403JSONResponse Error

func (response ConnectSessionGuest403JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionTokenRequestObject struct {
}

type ExchangeSessionTokenResponseObject interface {
	VisitExchangeSessionTokenResponse(w http.ResponseWriter) error
}

type ExchangeSessionToken200JSONResponse SessionCredential

func (response ExchangeSessionToken200JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExchangeSessionToken401JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuestsRequestObject struct {
}

type ListSessionGuestsResponseObject interface {
	VisitListSessionGuestsResponse(w http.ResponseWriter) error
}

type ListSessionGuests200JSONResponse []Guest

func (response ListSessionGuests200JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuests401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessionGuests401JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentityRequestObject struct {
}

type GetSessionIdentityResponseObject interface {
	VisitGetSessionIdentityResponse(w http.ResponseWriter) error
}

type GetSessionIdentity200JSONResponse Identity

func (response GetSessionIdentity200JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSessionIdentity401JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReservedRequestObject struct {
	Params IsLoginNameReservedParams
}

type IsLoginNameReservedResponseObject interface {
	VisitIsLoginNameReservedResponse(w http.ResponseWriter) error
}

type IsLoginNameReserved200JSONResponse struct {
	Reserved bool `json:"reserved"`
}

func (response IsLoginNameReserved200JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReserved401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IsLoginNameReserved401JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpointRequestObject struct {
}

type GetPublicEndpointResponseObject interface {
	VisitGetPublicEndpointResponse(w http.ResponseWriter) error
}

type GetPublicEndpoint200JSONResponse struct {
	Endpoint string `json:"endpoint"`
}

func (response GetPublicEndpoint200JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpoint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPublicEndpoint401JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeSessionCredentialRequestObject struct {
}

type RevokeSessionCredentialResponseObject interface {
	VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error
}

type RevokeSessionCredential204Response struct {
}

func (response RevokeSessionCredential204Response) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeSessionCredential401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSessionCredential401JSONResponse) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(ctx context.Context, request ConnectSessionGuestRequestObject) (ConnectSessionGuestResponseObject, error)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(ctx context.Context, request ExchangeSessionTokenRequestObject) (ExchangeSessionTokenResponseObject, error)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(ctx context.Context, request ListSessionGuestsRequestObject) (ListSessionGuestsResponseObject, error)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(ctx context.Context, request GetSessionIdentityRequestObject) (GetSessionIdentityResponseObject, error)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(ctx context.Context, request IsLoginNameReservedRequestObject) (IsLoginNameReservedResponseObject, error)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(ctx context.Context, request GetPublicEndpointRequestObject) (GetPublicEndpointResponseObject, error)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(ctx context.Context, request RevokeSessionCredentialRequestObject) (RevokeSessionCredentialResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectSessionGuest operation middleware
func (sh *strictHandler) ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64) {
	var request ConnectSessionGuestRequestObject

	request.GuestID = guestID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectSessionGuest(ctx, request.(ConnectSessionGuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectSessionGuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectSessionGuestResponseObject); ok {
		if err := validResponse.VisitConnectSessionGuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeSessionToken operation middleware
func (sh *strictHandler) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {
	var request ExchangeSessionTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeSessionToken(ctx, request.(ExchangeSessionTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeSessionToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeSessionTokenResponseObject); ok {
		if err := validResponse.VisitExchangeSessionTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSessionGuests operation middleware
func (sh *strictHandler) ListSessionGuests(w http.ResponseWriter, r *http.Request) {
	var request ListSessionGuestsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessionGuests(ctx, request.(ListSessionGuestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessionGuests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionGuestsResponseObject); ok {
		if err := validResponse.VisitListSessionGuestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessionIdentity operation middleware
func (sh *strictHandler) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {
	var request GetSessionIdentityRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessionIdentity(ctx, request.(GetSessionIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessionIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionIdentityResponseObject); ok {
		if err := validResponse.VisitGetSessionIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IsLoginNameReserved operation middleware
func (sh *strictHandler) IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams) {
	var request IsLoginNameReservedRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IsLoginNameReserved(ctx, request.(IsLoginNameReservedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IsLoginNameReserved")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IsLoginNameReservedResponseObject); ok {
		if err := validResponse.VisitIsLoginNameReservedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicEndpoint operation middleware
func (sh *strictHandler) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {
	var request GetPublicEndpointRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicEndpoint(ctx, request.(GetPublicEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicEndpointResponseObject); ok {
		if err := validResponse.VisitGetPublicEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeSessionCredential operation middleware
func (sh *strictHandler) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {
	var request RevokeSessionCredentialRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSessionCredential(ctx, request.(RevokeSessionCredentialRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSessionCredential")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeSessionCredentialResponseObject); ok {
		if err := validResponse.VisitRevokeSessionCredentialResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFv7bxtJcv5XGpMDNllQpPZ2kRy4v0TxGbYSxxYsGRtgx1g2Z4qcPs5Uz3b3iOIZ/t+DquqeBx+Wc+fL",
	"byI5j+7qr7766qFPWWGb1iJg8NnyU+bAtxY98IcPqLtQWWf+CiV9LiwGwEB/6ratTaGDsbj4i7dI3/mi",
	"gkbTX39wsMmW2T8thocv5Fe/eOmcddnnz59nWQm+cKalh2TL7KECFewOUBmvGuO9we1MwVNrHJQzpWsH",
	"ujyoztMn61SHO7R7nGf0qPh0evkLiwhFuMWNpY/Tl7x8BHcIlcGtQoASShWssi2gsghq24EP33lVWPS2",
	"hpnSWCq0cr1e2y4ojYecvgEnV9NKDPqgsYB5jtksa51twQUjNuSLnrPJK77o8yxLT3ruhtt43QsHJWAw",
	"uvZsBge/d2SubPlrfPPomR9nWTi0kC0zu/4LFPxCOY3lp6NVQ/p6ar0b5SvrgnKgvcW5+jPUZg1OB6gP",
	"ZCdVQtCmhnKpQgUeVA8npR3k6EAXlV7XoNawsQ6UVoWua3B05IQ12kuhA5RiyrhcH5zB7ckGZZHndvUq",
	"Gf14+XJk2iutWlPswDEKvDLhaDOFds6A7w8/VDqownZ1meMaGISEHN4Q7VWevFRaefDeWFSVrUuvQmW8",
	"qo0PakNACV7tK1tDjrXZRHw1llC0USaQFRAewREACcP8knOoMuXp7sh/nN0rU8769Wm/4xfr9ERjcZ7N",
	"so11jQ7ZMjMY/vWnwdIGA2zBjaF4y6/6P9zwVjdwurpbLOqO/M3b4dQLjYSovdhBh6JSFskQexMq9jbl",
	"obBYEnR+JwvP1S2biUxusT6oqW/2rnh0wLMc95UpKrp1X9Fd4IDNbRVg2VqDQc6Yzsr3j/FncTjLMO7x",
	"5IfW2afGPt1eOJ9EMKbkLRpkSNzJTf1bZwrm27n64fp6ftbSPujQiZ9i15AruA6RVkC/2baFcuQWw+Lk",
	"i+GugujhsTlz7ZGnmTKLe45X9msY73iCmSM8nPPSW6aucDg11S+VHXmS8TNyWQfe1o9Qqo2zDduNo8X8",
	"xDmK2gCGS0cgv37no6/M1c3aA4p/Eqp02Rg0PjgdrPtKXymNb2t9OI98fqnFjdl2Dkpl4q7JPRn79NLO",
	"g1sOr+fPigxOkS7HMF633SP/NFf05NpujXxmDkWla6PFP8TJciwq62FGjhcpxga1J6zTRR9uaRVdXaq4",
	"iQuIN/6GVjYC/draGjTSj7Tc8xsfLY/elo6U2JWOkpxgpnbQjuzflSbQffNnAwC/dmr9YaFnEXcmbJ5d",
	"dvLIYriwX2BPMZX1gcinVw7zHHN8IMaPDNXoAM7oegTmpvOBT2ANiiOhRJGI6lBBjqUOeq3pyCqNRJmW",
	"QoLQOImiGkZsTmdaaa/WAKgGuZZjsKrRu7OaRLfmgVxHXOTkqNPP91A4OBNG7xywx+wrwKlF4rK8rJh+",
	"urm7nZ+Dk27NB1efff2wt4cjvgrgGqKbA/GPr85ynPnacHWRwtGWF7y4Z6AED1FDdIN45Lmdel+9tqJG",
	"zv32X3CG/+5e/vcVYGHp8FtnHnUAtYPDTBmsDcJc3eDE6IlbyJ2UznEHB3V38/CacNgvmkPe+sBoE0kD",
	"amNI5a6h0J0HQV8CaqERbRBSoucZr8qxQrJd8KYEJmKWQReIw/vqzrrx/seRzFcfInd8fQSK2DlBSjy6",
	"c45/L5sa/P6stk07769iXcIIT6RtgvIt6B3TwTnfknzF34RzUQ3YXSlEe7W3bkfH4GCrXVmD9yQCO0+n",
	"2y/FdqE2j3JaxudInh6sgqei0rgFpbfa4ExFbRPioanSqqsrInxa+95gSaHO57gFBGc7rwBtt63oUQW7",
	"qla1xW3Ke5QOoT/Q3pVKHeAqmEEETN1uiOVfTFzSdSRHiGQu0wtL5xjK1qAdMQqnhxZVTcTKAc7P1Wtb",
	"lxzaMMcGGusOLA2Xqu0CEzT/xs8BfDTOYsP0xVGvw1LMJDlNjiYoeCIR+DUpiGxhNjr1kSlOgUiIh6Jz",
	"JhzuySACmXjYD+fNcRN33ZDblOTAK+LAVns/4vurHRz8qo9R5LAkZ3OcZFWScMSoEuwkJJOAthu11ljO",
	"1T0R21XNMVqT/Ja4c0XwpCA3yZXevntQJUhA5yim8ZCypuH5hcXgbO2XE5qJemb1h/v71799uH/5/reb",
	"Dw+vV0xMRDl2j7IEtXcmSOp4mBIVqYBZTCtqbRpFsbOMiQSnbBRrN9ZtU1rJYGQJw7AaTrkKoZXShDlb",
	"PRBFY9u1LnYU2iRlGM7Dg3uElYKn1nrOHaIckKesQcD8/fdp6Td3t99/vxQxpifP4d9XtDdJRkCXOdoN",
	"lyqSZZNOIAqGejPmDdch+45G1SFFEFPDFkrVmXievQyhNHV4ki4K8H4SEYYf6QS1wSFfubm7JZ1B6PSs",
	"FTyfVB+Z7u9fj8OXJ1IalJCk1BpF/piQI30IegeDfCjqzgdw0ZKgPAlJtrJTuvZW/hazvr2/V6VxUARi",
	"gH9eLQgYfjVT8teCosdiPp+vcqRVbpwBLP2/sM+sarNG738jAMy9nf9xRerakkUcTOOeoF3Os8yRoipD",
	"2jj1n/fv3ipf6ZahuzFP4q+0uPRwtTeOwdjoQN6o4CmAQ13nSOTbNeBUD4PSSgUi+c4sUrpxigDrlQ/6",
	"wO58Rd4RKLwQg6E8cqFbs+AL51tLas1BqmMg5TeU8xI4bdERIUKpEJ5C5IVmnuMrChc6RLw1kTGd8Tvl",
	"TQ0YalITqBtOwdXGQC2+unagObjBI7hDjpwFzNjSaNUaEDZG1PLNQE+S6ik9Jfuvob0+u0+wd5YFNpeY",
	"xhwkxJ6iupMLdmj3PobQHRyOKFOyrKko4kUp0uM1hSFLiozZO5a5/JQ91UCePytfWIFHYkxB8xVrqZQD",
	"9HpDUj+xxF5TXuE7YlnrZrFSdEq4sbbiCd3RcXRIduwLrL6lGGiaBkrDwJ4RY67u3t0/qEXc7iLpjBWf",
	"XY76nEaSsolmw3rRETFqx4vFhGFvVWk2GzZYjm3niCTlt7g4SqQkM/QpYA9hYhS6ZxHMXIttnS2ieAqJ",
	"IYjmRszCvIOloDEmyGkjvtIOPL06R7pNdJMkysO5yTGyyWLdJlWmOGYCqww+G95QjiP7mKDW3YFzwooc",
	"xKCKKiVF69psIK0/bYdZWo44+XYM2GMNQw8gs/odc0OS9iaoBjT69AUxntSs4+O/82kNTvP3odJSi1ot",
	"6JJF3l1f/1i0puQ/YBFfupqrd1J14wAsBkBgY69p8SzdoFQOWiD3IVyNKm86jAIAV+aWOa6d3XumECz7",
	"zJY+Ojr/R3C6Fqk3YzIkd7sYD2LoTUDmasrCtcVqtIwxnec44XNOkubqNni1tuVB+CjoLcdOpEUzlCgM",
	"O2EsLm20dedz1G7LROolBpSqJaz3V15dxSW8awFJPAyqoLXW1Qc5862QLnCG4HkxqjHOWSdOtSrX8/fQ",
	"Wm8ozq0Us/1GFyDBQco6OUod6cWbWz6bHUDLNkwkMdxlgtL1Xh+8EEdJi6xhWolQjSWfjBKxz/h+Vh7i",
	"o1K44de6tphv7WwUciS6nY05a2DqY+ayJcwVt2hGdhMhF1U3mXlMPnsO0j7YSWktll8mpbzvkqA3oSat",
	"10eTtH6SM9ksewTnRe39ML+eX1OiQqJLtyZbZj/Or+c/Us6nQ8XafVGBrkP1V271nCuWfJiGk2V04eAO",
	"UnRubV3HNkEMWD5ox/j3vipj2a7P/DT6Pbi+fYKHyOgxZSGwOHgEXfetC9l1b87bMltmryC85nVns2nH",
	"74/X10eNvgBPYdHW2hy1+OBJNy0b0u7OpElnu3vRUY1XXTufZEPZ8tePs8x3TaPdIVtmb8wjINFg6+xa",
	"6ip66ynjEntnH+nuPk5F0lh84jLcbfmZO1r2XA/oPYTOoeDjUpXv3duXUtCbKb3hRLOCYpfaQBSTjU9h",
	"ttGH2AUyQYIZX8w9TF0CE8psHORnHLIlsB/hdhkjSaoLMrfo2LSKhdsWHPdGSUDb2FFT5rT0yM2RaWvD",
	"xa1HrS7JoBm+p1tkXSclTpawuoEyFjpHqcYgpLjjNQ59Yk1mfQmoI3IPdjaJPSkWxvbYWPjfIGcSlNOO",
	"al3SxNOhkiKXFqkleyGbxkrZw2lNS65mk3CaeXWViqgkTjtvGHnTo7i6ypEDLD0+WYTfvk8ZZueBqzjB",
	"ynmceF1sTMda1KvYnm210w0EcATvL/WMUm9Pe7Ul92BN3LsAX+VXc268EL1p9m6pcmbRL7Jx9SK4DmYj",
	"j362Zvr547Ns8bePBYy79hfoIzZvY0nuGGZm1LabE2v/dP3DpZf2u1hMRhz4ph//fyYdRvQRIcmNZOOT",
	"h01KLL2yFf7PUfvYEBCjMJj7dJGDwVIF6ON9o3SrXap5EYYji/UMYZCii9prbkwBUiZKefs0CxfS7mn6",
	"l+jalLT7fpJi2MUwSjGm8AjZIw5PucZl6n4hCXLMLQZtLhHwC1WxtksFwHHdaayjB+ogVpkkN5Pkj5w8",
	"x8RVDnwviKSfH+wWmNO4En9cOV4DZUdeevo5jirOuhcBlvu/OogM6NpZAjxKCSvEzhJnTLH6MlcvorSj",
	"s9ibAob3M2rEQhttpPxGGjHmgTlyVnOOrl7GA7kflyf/gQxwWqO/4DoI++Ma/b5KOdvGur/V+yfQfnA6",
	"qtJJ5hy7cCdZ8PP4FoK+qBNv4njTxtQBXBKKUTGVUJgS/FAfEPbgQQKBF+lEksaJDi4QTBQRMbmOYpKS",
	"srqO0Zh4gZM5glNtfIAUWDc8VMKVdxE6E3lNqYBP9Z6hG/qin6MZE3YU+VKzSKMYMTuczOWQxCmd3ivN",
	"a/m5FxNTxtF956KwTbRTjkfFjBORuJoNrVs2ggqmgXOu8Mb4Sdj2f68fmACN/+qpsBiItXP6cMkphtEq",
	"Adq3cYIUdSM59U3sJHqfh/24MXQW+A8DEIfDU33ZS3L+Z6tcA5dqv4urjXVzYmh2ILo1KgWoN8tB9OUY",
	"XOfD3rpQHVII3KHdD1XB6XRaL7gZhef4QJZ9TB+RfAl1qQSXI8m4i2U3WUCafXSj5CUZlnyReJzLS1Jb",
	"Hgas+HUyiaZPOFMjz9AoB1esiPeV5fYX+WKcv6o0Nx95QGNgjAspZfSQvsX3D4wVQxvxS+pqxI/fxB1+",
	"qWyPPclhKCSMovqz3sCF8CsS5VcOmNzLLzvGtIIRM8K+lDlKh2Q8KF4gs5byfK4grLwnFJkC/p1SuhXT",
	"puAo8u3IWWprd9FXhpASi0N5xk/JM1EwfhfLtvLexKHKopoUePuhSMraIpjXAKRCbV326SWlNPvKctWT",
	"SI8cTVp7jLth0q93oxr0zueYxjS5xgYOeFxsnKrxCGZUv1DXyX5iNAY+1B4mnd8pvm/9Gzq7t7qB9+nk",
	"TpI3zrx+78AdhtQrDi1czruOSyd/b5Y1nUcYw+x4cOuomd1feqZxfdbLHsGVpgjfyLdEOOvxyJgUsfOM",
	"K8SQZ5OKQZ7mP/Lsecdru3VtiquU7lx0uvvK7jHpoyQqZNZRrbWbnzZ7HRTWlQzV1DbN0fuq5Cx9HB20",
	"2jjw1bST4e1xjpEqFDnevX/3P3c39/e/3X34jze3L357+fbPd+9u3z6khi+54MumDYdhFKuEtrYHzmkk",
	"tgWZDGM3i+JpnPX5n1nw9eUljYrHqvu0g3atvGna+sDjiryhyroATtV6DfWFYHDHBn+Z7P1NMT0+xWdG",
	"xNOVXwvpdMNMtdZ7s64PCsjC30xOEf0ytoV7vJIMdlwASAh7HtUOHu3uSxlzqugDjnBIkqkH3kgUTOeS",
	"mGALCiQjn0v4eWqNO0yrgDqokpR+kg5Dt4HUSQ1anOG4cRgnZ6TKz/Me5wD1njd6miGewOqnC/O3o3ac",
	"V1uLPFjLLVXpsXEV85sc8ivzCKprJ4L5O/98qjithh9PBf36keKCpIPnCoVv0lSKxfoQJ4MpeUOpt8sm",
	"17ZD+bcA5Wwn0zS6LB2PfMiYD/GWpHpetdbxWO5eu5L/FydChkvLQ74hWiu2vmN/EYYwb3DU3+EBkiQg",
	"O1fHmZvlYvHDH/9tfj2/nv+w/NP1n64z2m000ukYHesMliVXPUWPe4oz6bKXUoodi8A+KifDf559Sl/F",
	"zsLnj5//NwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
