//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GuestStatus.
const (
	Running GuestStatus = "running"
	Stopped GuestStatus = "stopped"
)

// Valid indicates whether the value is a known member of the GuestStatus enum.
func (e GuestStatus) Valid() bool {
	switch e {
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for GuestType.
const (
	Ct GuestType = "ct"
	VM GuestType = "vm"
)

// Valid indicates whether the value is a known member of the GuestType enum.
func (e GuestType) Valid() bool {
	switch e {
	case Ct:
		return true
	case VM:
		return true
	default:
		return false
	}
}

// Defines values for InstanceCredentialsConnectionType.
const (
	SSH       InstanceCredentialsConnectionType = "ssh"
	Termproxy InstanceCredentialsConnectionType = "termproxy"
)

// Valid indicates whether the value is a known member of the InstanceCredentialsConnectionType enum.
func (e InstanceCredentialsConnectionType) Valid() bool {
	switch e {
	case SSH:
		return true
	case Termproxy:
		return true
	default:
		return false
	}
}

// ConnectInfo Everything needed to open one guest's console, and nothing about any
// other guest or instance.
type ConnectInfo struct {
	// Guest A guest as a picker needs it. Deliberately carries nothing that could
	// be used to reach the guest: a session holds this list for its whole
	// life, and most of it is never connected to.
	Guest Guest `json:"guest"`

	// Instance The Proxmox credentials for the instance hosting one guest.
	//
	// This is the material a session must not be able to read from the
	// database, handed over for a single connection it has been authorized
	// to make.
	Instance InstanceCredentials `json:"instance"`
}

// Error defines model for Error.
type Error struct {
	// Error A short reason. Deliberately not detailed: these responses are
	// reachable before a caller is authenticated.
	Error string `json:"error"`
}

// Guest A guest as a picker needs it. Deliberately carries nothing that could
// be used to reach the guest: a session holds this list for its whole
// life, and most of it is never connected to.
type Guest struct {
	// ID The row id, used to ask for a connection.
	ID         int64 `json:"id"`
	InstanceID int64 `json:"instanceId"`

	// InstanceName Included so a caller can show and match on it without a second
	// request. It is the only thing about an instance a picker needs,
	// which is why there is no endpoint that lists instances.
	InstanceName string `json:"instanceName"`
	Name         string `json:"name"`

	// ProxmoxID The guest's id within its Proxmox instance, e.g. 100.
	ProxmoxID int         `json:"proxmoxId"`
	Status    GuestStatus `json:"status"`
	Type      GuestType   `json:"type"`
}

// GuestStatus defines model for Guest.Status.
type GuestStatus string

// GuestType defines model for Guest.Type.
type GuestType string

// Identity Who a session is, as resolved from its token.
type Identity struct {
	// ClientID The client's row id. Absent for the administrator.
	ClientID *int64 `json:"clientId,omitempty"`

	// IdentityName Who the caller IS: the client's own name, or the administrator's.
	// Resolved by `proxpass authorized-keys`, which runs as root before
	// the session exists and therefore knows which key authenticated,
	// so the session cannot influence it. This is the name to log and
	// the name to show.
	IdentityName string `json:"identityName"`
	IsAdmin      bool   `json:"isAdmin"`

	// LoginName What the caller typed in `ssh <name>@host`. A REQUEST PARAMETER,
	// not an identity: any name the directory does not already serve
	// resolves to an alias, so anybody can pick anybody else's. The
	// session also accepts it as a guest target ("ssh ct100@host").
	// Never log it as the actor and never authorize from it.
	LoginName string `json:"loginName"`
}

// InstanceCredentials The Proxmox credentials for the instance hosting one guest.
//
// This is the material a session must not be able to read from the
// database, handed over for a single connection it has been authorized
// to make.
type InstanceCredentials struct {
	APITokenID *string `json:"apiTokenId,omitempty"`

	// APITokenSecret Present when the instance connects over the API.
	APITokenSecret *string                           `json:"apiTokenSecret,omitempty"`
	APIURL         string                            `json:"apiUrl"`
	ConnectionType InstanceCredentialsConnectionType `json:"connectionType"`
	ID             int64                             `json:"id"`
	Name           string                            `json:"name"`

	// Node The resolved Proxmox short node name.
	Node    string  `json:"node"`
	SSHHost *string `json:"sshHost,omitempty"`

	// SSHKey PEM-encoded private key, inline. An instance configured with a
	// key PATH is resolved here by reading the file, because the
	// session cannot: the key is deliberately outside its reach.
	SSHKey  *string `json:"sshKey,omitempty"`
	SSHPort *int    `json:"sshPort,omitempty"`
	SSHUser *string `json:"sshUser,omitempty"`
}

// InstanceCredentialsConnectionType defines model for InstanceCredentials.ConnectionType.
type InstanceCredentialsConnectionType string

// SessionCredential A session credential and the identity it speaks for.
type SessionCredential struct {
	// ExpiresAt When it stops working regardless of use. A session outliving this
	// has to exchange again, which it cannot do -- so the window is
	// generous enough to cover a long console attach.
	ExpiresAt time.Time `json:"expiresAt"`

	// Identity Who a session is, as resolved from its token.
	Identity Identity `json:"identity"`

	// Token Present this as the bearer token on later calls. Hold it in
	// memory only: putting it in the environment would undo the reason
	// it exists.
	Token string `json:"token"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// IsLoginNameReservedParams defines parameters for IsLoginNameReserved.
type IsLoginNameReservedParams struct {
	Name string `form:"name" json:"name"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(w http.ResponseWriter, r *http.Request)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(w http.ResponseWriter, r *http.Request)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(w http.ResponseWriter, r *http.Request)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(w http.ResponseWriter, r *http.Request)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectSessionGuest operation middleware
func (siw *ServerInterfaceWrapper) ConnectSessionGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guestId" -------------
	var guestID int64

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", r.PathValue("guestId"), &guestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectSessionGuest(w, r, guestID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeSessionToken operation middleware
func (siw *ServerInterfaceWrapper) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeSessionToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessionGuests operation middleware
func (siw *ServerInterfaceWrapper) ListSessionGuests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessionGuests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IsLoginNameReserved operation middleware
func (siw *ServerInterfaceWrapper) IsLoginNameReserved(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IsLoginNameReservedParams

	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IsLoginNameReserved(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicEndpoint(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSessionCredential operation middleware
func (siw *ServerInterfaceWrapper) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSessionCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/exchange", wrapper.ExchangeSessionToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/revoke", wrapper.RevokeSessionCredential)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/guests", wrapper.ListSessionGuests)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/connect/{guestId}", wrapper.ConnectSessionGuest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/login-name-reserved", wrapper.IsLoginNameReserved)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/public-endpoint", wrapper.GetPublicEndpoint)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/identity", wrapper.GetSessionIdentity)

	return m
}

type UnauthorizedJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type ConnectSessionGuestRequestObject struct {
	GuestID int64 `json:"guestId"`
}

type ConnectSessionGuestResponseObject interface {
	VisitConnectSessionGuestResponse(w http.ResponseWriter) error
}

type ConnectSessionGuest200JSONResponse ConnectInfo

func (response ConnectSessionGuest200JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ConnectSessionGuest401JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest403JSONResponse Error

func (response ConnectSessionGuest403JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionTokenRequestObject struct {
}

type ExchangeSessionTokenResponseObject interface {
	VisitExchangeSessionTokenResponse(w http.ResponseWriter) error
}

type ExchangeSessionToken200JSONResponse SessionCredential

func (response ExchangeSessionToken200JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExchangeSessionToken401JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuestsRequestObject struct {
}

type ListSessionGuestsResponseObject interface {
	VisitListSessionGuestsResponse(w http.ResponseWriter) error
}

type ListSessionGuests200JSONResponse []Guest

func (response ListSessionGuests200JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuests401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessionGuests401JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentityRequestObject struct {
}

type GetSessionIdentityResponseObject interface {
	VisitGetSessionIdentityResponse(w http.ResponseWriter) error
}

type GetSessionIdentity200JSONResponse Identity

func (response GetSessionIdentity200JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSessionIdentity401JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReservedRequestObject struct {
	Params IsLoginNameReservedParams
}

type IsLoginNameReservedResponseObject interface {
	VisitIsLoginNameReservedResponse(w http.ResponseWriter) error
}

type IsLoginNameReserved200JSONResponse struct {
	Reserved bool `json:"reserved"`
}

func (response IsLoginNameReserved200JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReserved401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IsLoginNameReserved401JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpointRequestObject struct {
}

type GetPublicEndpointResponseObject interface {
	VisitGetPublicEndpointResponse(w http.ResponseWriter) error
}

type GetPublicEndpoint200JSONResponse struct {
	Endpoint string `json:"endpoint"`
}

func (response GetPublicEndpoint200JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpoint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPublicEndpoint401JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeSessionCredentialRequestObject struct {
}

type RevokeSessionCredentialResponseObject interface {
	VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error
}

type RevokeSessionCredential204Response struct {
}

func (response RevokeSessionCredential204Response) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeSessionCredential401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSessionCredential401JSONResponse) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(ctx context.Context, request ConnectSessionGuestRequestObject) (ConnectSessionGuestResponseObject, error)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(ctx context.Context, request ExchangeSessionTokenRequestObject) (ExchangeSessionTokenResponseObject, error)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(ctx context.Context, request ListSessionGuestsRequestObject) (ListSessionGuestsResponseObject, error)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(ctx context.Context, request GetSessionIdentityRequestObject) (GetSessionIdentityResponseObject, error)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(ctx context.Context, request IsLoginNameReservedRequestObject) (IsLoginNameReservedResponseObject, error)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(ctx context.Context, request GetPublicEndpointRequestObject) (GetPublicEndpointResponseObject, error)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(ctx context.Context, request RevokeSessionCredentialRequestObject) (RevokeSessionCredentialResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectSessionGuest operation middleware
func (sh *strictHandler) ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64) {
	var request ConnectSessionGuestRequestObject

	request.GuestID = guestID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectSessionGuest(ctx, request.(ConnectSessionGuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectSessionGuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectSessionGuestResponseObject); ok {
		if err := validResponse.VisitConnectSessionGuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeSessionToken operation middleware
func (sh *strictHandler) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {
	var request ExchangeSessionTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeSessionToken(ctx, request.(ExchangeSessionTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeSessionToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeSessionTokenResponseObject); ok {
		if err := validResponse.VisitExchangeSessionTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSessionGuests operation middleware
func (sh *strictHandler) ListSessionGuests(w http.ResponseWriter, r *http.Request) {
	var request ListSessionGuestsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessionGuests(ctx, request.(ListSessionGuestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessionGuests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionGuestsResponseObject); ok {
		if err := validResponse.VisitListSessionGuestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessionIdentity operation middleware
func (sh *strictHandler) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {
	var request GetSessionIdentityRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessionIdentity(ctx, request.(GetSessionIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessionIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionIdentityResponseObject); ok {
		if err := validResponse.VisitGetSessionIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IsLoginNameReserved operation middleware
func (sh *strictHandler) IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams) {
	var request IsLoginNameReservedRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IsLoginNameReserved(ctx, request.(IsLoginNameReservedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IsLoginNameReserved")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IsLoginNameReservedResponseObject); ok {
		if err := validResponse.VisitIsLoginNameReservedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicEndpoint operation middleware
func (sh *strictHandler) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {
	var request GetPublicEndpointRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicEndpoint(ctx, request.(GetPublicEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicEndpointResponseObject); ok {
		if err := validResponse.VisitGetPublicEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeSessionCredential operation middleware
func (sh *strictHandler) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {
	var request RevokeSessionCredentialRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSessionCredential(ctx, request.(RevokeSessionCredentialRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSessionCredential")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeSessionCredentialResponseObject); ok {
		if err := validResponse.VisitRevokeSessionCredentialResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vHtvk9u4kf5XQfGXKidbFDXe3fpdSvvm5pwpe+4ce84zrlzV0rWCyJaIiAS4ADgaZcvf/aq7Af6RKI+T",
	"OPduJPEP0Oh++nm6e35LCtO0RoP2Lln9llhwrdEO6MNHLTtfGav+BiV+Loz2oD3+Kdu2VoX0yujlX53R",
	"+J0rKmgk/vU7C9tklfy/5fDwJf/qljfWGpt8/vw5TUpwhVUtPiRZJQ8VCG/2oIVyolHOKb1LBTy1ykKZ",
	"CllbkOVRdA4/GSs6vdfmoLMEHxWeji9/ZbSGwt/qrcGP05fcPII9+krpndAAJZTCG2Fa0MJoELsOnH/h",
	"RGG0MzWkQupSaMPXy43pvJD6mOM3YPlqXInSzktdQJbrJE1aa1qwXrEN6aLnbPKaLvqcJvFJz91wG657",
	"ZaEE7ZWsHZnBwq8dmitZ/RzePHrmpzTxxxaSVWI2f4WCXsinsfrtZNUQv55a71q4ylgvLEhndCb+BLXa",
	"gJUe6iPaSZTgpaqhXAlfgQPRu5OQFnJtQRaV3NQgNrA1FoQUhaxrsHjk6Gu4l0J6KNmUYbnOW6V3Zxvk",
	"Rc7t6nU0+uny+cikE1K0qtiDJS9wQvmTzRTSWgWuP3xfSS8K09VlrjdAToieQxvCvfKTV0IKB84po0Vl",
	"6tIJXyknauW82KKjeCcOlakh17XaBv9qDHrRViiPVtDwCBYdEH2YXjLnVao83x3GjzUHocq0X590e3qx",
	"jE9URmdJmmyNbaRPVonS/v//OFhaaQ87sGNXvKVX/R03vJMNnK/uVhd1h/HmzHDqhdToUQe2g/RFJYxG",
	"QxyUryjahIPC6BJd51e0cCZuyUxocqPro5jGZh+KJwec5vpQqaLCWw8V3gUWyNxGgC5bo7TnM8azcv1j",
	"3KwfpokOezz7obXmqTFPtxfOJwKMKmmLSpNL3PFN/VtTAdkuEy+vrrJZSzsvfcdxqrsGQ8F2WuMK8DfT",
	"tlCOwmJYHH8x3FUgPDw2M9eeRJoqk7DncGW/hvGOJz5z4g9zUXpL0OWP56b6S2VGkaRciiFrwZn6EUqx",
	"taYhu1G2yM6Co6gVaH/pCPjXFy7ESiauNw40xyd6lSwbpZXzVnpjvzZWwk7mXR93g08OTn97v+KPcSHm",
	"oAUal7La2RJeoA9+iHvfHMUaLd5Kx4jJ2Xmxh6Nbp4Kd3HbakcWM8QFpc40PjhaFJ/JyjDqKBMJizKYu",
	"PGEPxykep7l2vIv4jEJqRHylt3UHGHGIoQ8IdyE8cUuIQbXZ4Zt4BfFLjPoLsaXcNe5/FF4bY2qQGn+s",
	"zU7pS2aWfmxnvLkUSou1c5XIu6urHwp8Pf0F/14Z59eZuBYfbv774839g7i7/nD955uHmw9pTjtDNAnn",
	"usK0H9ZegSiVhcIbexSl4RzRsxMH9pESHZ2XIwzWQtZKupSgTx83pjwS8iFA9V9A7eCFQwtCrqONZY23",
	"FAW0iEkhcXEO89LuwIvf5wnurvAvr65oS3nyhyzX7yiLoOX5LvIqXDIzGvq1954YUF+Tcwf7n3j9cG6z",
	"oT7DV2ajM0JhMVzYR2aP7bhPRP2esmW5zvXY9xrpwSpZj1Ck6Zyno9qAIArC6TvAiUezl9LLjXSQikpq",
	"zFUG7cT5E9loDaM0ipatpBMbAD2KxFx7Ixq5nyWDslUPiFmMTWeeH3++h8LCDH+5s0BQdahATy0SluV4",
	"xfjT9d1tNhddslUfbT37+mFvDyeJwoNtEHWOCPyumk0u6mt5wsXcqU0JF2hNhL/oHkxD8QaKytmdOle9",
	"MUwD5377L5hJPHc3f16ALgwefmvVo/SAWJgKpWulIRPXemL0rdp1FjiZC5lrxM2764c36If9oolrbI7k",
	"bcwlQWwVyosNFLJzwN43BVbOEfg85UQ5pqam806VQBmQ+OcFHHWuujN2vP8xhXDVRwd2xjhfSP3Bd848",
	"JRzdXODf86aGuJ8VFXHn/VUxNfUIjNHmWpB7goO52GKh6K79XGYAClfkRk4cjN3jMVjYSVvW4Byy787h",
	"6fZLMZ2v1SOflnK5xkj3RsBTUUm9AyF3UumYb5WP2bA0YrEQIVMelC6RY7hc70CDNZ0ToE23q/BRBYWq",
	"FLXRuyg4hfS+P9A+lErpYeHVwL6mYTeQqC8qxngd8kAEmcvwQpolJI0NSIuIQrrcaFEjsFKGdZl4Y+qS",
	"ZIvOdQMNJkTk5CvRdp4Amn6j54B+VNbohuALZZTodMlmYjGZa+UDL/maPMRbSEenPjLFuSOix0PRWeWP",
	"92gQdplw2A/z5rgOu24wbJ5hXn2OwoBFHZHrKX0ihw5ZxU+JFCoXsxUbqctM3COwLWqFuEGkifPOAt0T",
	"k9xEpL57/yBKsKonxVIfo1wdETWjvTW1W01gJvDO9e/u79/88vH+5sMv1x8f3qwJmBByzEHzEsTBKs+a",
	"/TgFqs6BTYOeq6VqBObOMig40sqYa7fG7qKeJ2ckRkduNZxy5X3LNSE1W7bBJFAb025kscfUxlptOA+i",
	"XWsBT61xJNoCHeCnbICd+bvv4tKv726/+24lDvgUOXkO/b7GvbEKBFnm2mypRhQtG3kCQjDU2zFuROot",
	"teg0ZhBVww5K0alwnj0NqTB4+ichyXNukhGGH/EEpdKDULy+u0Wegd7piCswl+8z0/39m3H6cghKAxPi",
	"WobUTH+UzzV+8HIPA30o6s55sMGSIBxyX7KyZVZKf7NZ393fjyjx79dLdAxUI/zXErPHMsuyda5xlVur",
	"QJfuDxQz61pttHO/oANkzmTfr5ECG7SIhWneY2/n8yxzjVmVXFpZ8Z/3798JV8mWXHernjheSXCEh4uD",
	"suSMjfQYjQKePFgt61wj+HYNWNG7QU/rQ+ykAdIVqwonnJdHCucFRofH9IIIpvmRS9mqJV2Y7QyyNQux",
	"gKRR1SlNNYzSFB0CIiAjf/IBF5os168xXUgf/K0JiGmV2wunatC+RjahZUO1D7FVUHOsbixISm7I8I+5",
	"JrqekqW1ERvQsFXMlq8HeGKNLeQU7L8G9vqyyoziFH+v4DyBTJJCp2oTF4UqWdaYhgwyMkLvUF90U/QU",
	"A3j+JFxh2D0iYrI3L4hLRQ3Q8w1Wq2yJg0Rd4TpEWWPTIJ/OATfoTofeHQJH+mjHvrLtWsyBqmmgVOTY",
	"KSLm+u79/YNYhu0uI89Y09nlWs5xJK5XSTKsYx4Rsna4mE3oD0aUarslg+W67SyCJP8WFodCSlo0i4sJ",
	"e0gTo9SdBmemInhrTRHIk48IgTA3QhbCHV2yN7IK7jfiKmnB4atzjbcxb+Ii6HBufIxkslAwiyVByplA",
	"LIPOJkjnkX2UF5vuSJqwwgBRWgSWErN1rbYQ1x+3QyjNRxxjOyTsMYfBB6BZ3Z6wIVJ75UUDUrv4BSIe",
	"NwvC41+4uAYr6XtfSS4Crpd4yZLrFK0quUyxDC9dZ+I9lzspAbMBNJCxN7h4om5QCgstYPigX41KntKP",
	"EgCVRFe53lhzcAQhuuyVLX60eP6PYGXNVC8lMMRwu5gPQuqNjkwlrKVti/VoGWM4z/UEz0kkZeLWO0Hl",
	"EMIjL3eUOzUumlwJ07BlxKJqTFt3LtfS7ghIHeeAUrTo6/2Vi0VYwvsWNJKHgRW0xtj6yGe+Y9AFUgiO",
	"FiMaZa2xHFTrcpN9gNY4hXluLQjtt7IATg5cfMo17Vy8entLZ7MHaMmGESSGu5QXsj7Io2PgKHGRNUwr",
	"EaIxGJOBIvaK7yfhIDwqpht6rW2LbGfSUcrh7DabczZA0EfIZUrIBPXGRnZjIhdYN5p5DD4HStLOG5S/",
	"g0pzFwqYSPWUr5Hr9dkkrh/pTJImj2Ads72X2VV2hUIFSZdsVbJKfsiush9Q80lfEXdfViBrX/2Nemxz",
	"xZKP03SyCiHs7ZGr/a2p69CfCQnLeWnJ/52rypTRqFd+UrsD2L5vpY8B0YNkQWex8Aiy7ntGvOvenLdl",
	"skpeg39D607Saav1+6urkw6rhye/bGupTnqr8CSblgxp9jMyabatGgJVOdG12UQNJaufP6WJ65pG2mOy",
	"St6qR9AIg601G66ryJ1DxcX2Tj7h3X2eCqCx/I3KcLflZ2olmrnm2wfwndXsH5eqfO/f3XBBLxVyS0Kz",
	"gmIf+2+Yk5WLabaRx9B+48Iz8MXUPJYlEKCk4ySfUsoOhfCp365CJol1QcKWWGlVTAVbsNSURgJtQitT",
	"qPPSI3Wlpj0lG7YeuDqLQTV8j7fwus5KnLFmXoZC50hqDESKWo3j1MfWJNTnhDoCd2/SSe6JuTD0JcfE",
	"/1qTkkBNO6p1cfdU+oqLXJKpFu+FCu5cKXs4r2nx1WQSkpmLRSyiIjntnCLPmx7FYkGdB358tAi9/RAV",
	"ZueAqjje9EXsadSFiYBQi3od+uKttLIBDxbd+0vNuthUlU7sMDyIE/chQFe5dUYdL4Q3SdHNVc4kxEUy",
	"rl5420E6iuhna6afPz2LFv/4PMZ4XOICfISueSjJnbqZGvVLM0TtH69eXnppv4vlZLaEbvrh/2bEZAQf",
	"wSWpg69cjLBJiaVntoz/uZYuNARCGwaduZeLlAxWwkOf7xshW2ljzQt9OKBYjxBKY3YRB3mkAqNGJYq6",
	"farCGbR7mP5LCG0U7a4fYRl2McywjCE8uOwJhketcRm6X7FADtpi4OacAb9QFWu7WAAc153GPHqADkSV",
	"ibiZiD8M8lxHrLLgekLEgxTe7IAwjSrxp5XjDaA6cjxMketRxVn2JMBQ4116pgFdm0aH11zC8qGzRIop",
	"VF8y8SpQOzyLgypgeL/jTidaaCsVl9+QIwYdmGtSNXNwdRMO5H5cnvwXIsB5jf5C6Gg4nNboD1XUbFtj",
	"/9Hon7j2g5WBlU6Uc+jCnang5/2bAfoiT7wOndutqj3YSBQDYyqhUCW4oT7A6EETHOxeyBORGkc4uAAw",
	"gUQEcR3IJIqyug7ZGHGBxBy6U62ch5hYtzTNQ5V3JjoTeo1SwMV6z9ANfdUPMI0BO5B8rlnEGZigDicD",
	"UUhxSisPQtJafurJxBRxZN+5KEwT7JTrk2LGGUlcp0PrlowgvGpgLhTeKjdJ2+6fjQPloXFfPY4XErG0",
	"Vh4vBcUw08aO9m2CIGbdAE59EzuS3ufdftwYmnX8h8ERh8MTfdmLNf+zVa4BS6Xbh9WGujkiNAUQ3hqY",
	"AtTb1UD6cu1t5/zBWF8dYwrca3O4NIbSE27ywjk84GWfwkcAX/S6WILLNdK4i2U3XkAc67Aj8RINy9Mu",
	"uabyEteWh8k2eh2PAMozzJSahpeEhQUx4kNlqP2FsRgG3ypJzcc9tH6EGBckZYiQvsX3L8wVQxvxS+xq",
	"hI/fJBzGE1SsYTAljLL6s9FAhfAFkvKFBQL38suBMa1gBEXYlzJHcojHuMIFPOTKz6cKAs0eyVoVYeCI",
	"YJP9KODtKFhqY/YhVoaUEopDeUJPyRNmMG4fyrb83oihwmgxKfD206io2oIzbwCQhZq6HOa0Nkf0Qqp6",
	"hrkpH+aV0O+GEcs+jGqQe0eDUoQMVGMDCzSnN5ZqNPsa2C/UdbQfG40cH2oHk87v1L9v3ds4c/QhntyZ",
	"eCPl9WsH9jhIrzC0cFl3nZZO/lmVNZ1HGLvZ6RzbSTO7v3SmcT0bZY9gS1X4bxRbTJyloBhhd+Aidp5Q",
	"hRjyZFIxyOP8R548H3htt6lVsYhy52LQ3VfmoCM/iqSCh0zFRtrsvNlroTC2JFeNbdNcO1eVpNLH2UGK",
	"rQVXTTsZ8+OMlvq9dx/e/8/d9f39L3cf/+Pt7atfbt796e797buH2PDFELxpWn8cRrFKaGtzJE3Duc3z",
	"ZBiFWSBPY9XnfiLC15eXpBY0z97LDty1cKpp6yNNS9KGKmM9WFHLDdQXksEdGfwm2vub+vT4FJ+ZzY9X",
	"fq1LxxtS0Rrn1KY+CkALfzM6hfBLvs3Y4wQr2HEBIHrY815t4dHsv6SYY0Uf9MgPkTL1jjciBdO5JALY",
	"AhPJKOai/zy1yh6nVUDpRYlMP1KHoduA7KQGycFw2jgMkzNc5ad5jzmH+kAbPVeIZ27144Vp61E7zomd",
	"0TzlfJDxPx2oivlNDvm1egTRtRPC/MI9LxWn1fDTqaCfP2FeYDk4Vyh8G6dSjK6PnHNJvGmut/MmN6bT",
	"/P8YwpqOp2lkWVoa+eAxH8QtlnpOtMbSPPpB2pL+CSq4DJWWB73BXCu0vkN/EYY0r/Sov0MDJJFAdrYO",
	"Mzer5fLl9/+WXWVX2cvVH6/+eJXgboORZgesAy1Z9BA97imm3GUvuRQ7JoF9Vo6G/5z+Fr8KnYXPnz7/",
	"bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
