//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GuestStatus.
const (
	Running GuestStatus = "running"
	Stopped GuestStatus = "stopped"
)

// Valid indicates whether the value is a known member of the GuestStatus enum.
func (e GuestStatus) Valid() bool {
	switch e {
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for GuestType.
const (
	Ct GuestType = "ct"
	VM GuestType = "vm"
)

// Valid indicates whether the value is a known member of the GuestType enum.
func (e GuestType) Valid() bool {
	switch e {
	case Ct:
		return true
	case VM:
		return true
	default:
		return false
	}
}

// Defines values for InstanceCredentialsConnectionType.
const (
	SSH       InstanceCredentialsConnectionType = "ssh"
	Termproxy InstanceCredentialsConnectionType = "termproxy"
)

// Valid indicates whether the value is a known member of the InstanceCredentialsConnectionType enum.
func (e InstanceCredentialsConnectionType) Valid() bool {
	switch e {
	case SSH:
		return true
	case Termproxy:
		return true
	default:
		return false
	}
}

// ConnectInfo Everything needed to open one guest's console, and nothing about any
// other guest or instance.
type ConnectInfo struct {
	// Guest A guest as a picker needs it. Deliberately carries nothing that could
	// be used to reach the guest: a session holds this list for its whole
	// life, and most of it is never connected to.
	Guest Guest `json:"guest"`

	// Instance The Proxmox credentials for the instance hosting one guest.
	//
	// This is the material a session must not be able to read from the
	// database, handed over for a single connection it has been authorized
	// to make.
	Instance InstanceCredentials `json:"instance"`
}

// Error defines model for Error.
type Error struct {
	// Error A short reason. Deliberately not detailed: these responses are
	// reachable before a caller is authenticated.
	Error string `json:"error"`
}

// Guest A guest as a picker needs it. Deliberately carries nothing that could
// be used to reach the guest: a session holds this list for its whole
// life, and most of it is never connected to.
type Guest struct {
	// ID The row id, used to ask for a connection.
	ID         int64 `json:"id"`
	InstanceID int64 `json:"instanceId"`

	// InstanceName Included so a caller can show and match on it without a second
	// request. It is the only thing about an instance a picker needs,
	// which is why there is no endpoint that lists instances.
	InstanceName string `json:"instanceName"`
	Name         string `json:"name"`

	// ProxmoxID The guest's id within its Proxmox instance, e.g. 100.
	ProxmoxID int         `json:"proxmoxId"`
	Status    GuestStatus `json:"status"`
	Type      GuestType   `json:"type"`
}

// GuestStatus defines model for Guest.Status.
type GuestStatus string

// GuestType defines model for Guest.Type.
type GuestType string

// Identity Who a session is, as resolved from its token.
type Identity struct {
	// ClientID The client's row id. Absent for the administrator.
	ClientID *int64 `json:"clientId,omitempty"`

	// DisplayName The configured identity to show the user: the admin user name, or
	// the client's own name. The login name is an alias the caller
	// chose, so it is not what the UI should display.
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`

	// User The login name the session arrived with, kept for the audit log.
	User string `json:"user"`
}

// InstanceCredentials The Proxmox credentials for the instance hosting one guest.
//
// This is the material a session must not be able to read from the
// database, handed over for a single connection it has been authorized
// to make.
type InstanceCredentials struct {
	APITokenID *string `json:"apiTokenId,omitempty"`

	// APITokenSecret Present when the instance connects over the API.
	APITokenSecret *string                           `json:"apiTokenSecret,omitempty"`
	APIURL         string                            `json:"apiUrl"`
	ConnectionType InstanceCredentialsConnectionType `json:"connectionType"`
	ID             int64                             `json:"id"`
	Name           string                            `json:"name"`

	// Node The resolved Proxmox short node name.
	Node    string  `json:"node"`
	SSHHost *string `json:"sshHost,omitempty"`

	// SSHKey PEM-encoded private key, inline. An instance configured with a
	// key PATH is resolved here by reading the file, because the
	// session cannot: the key is deliberately outside its reach.
	SSHKey  *string `json:"sshKey,omitempty"`
	SSHPort *int    `json:"sshPort,omitempty"`
	SSHUser *string `json:"sshUser,omitempty"`
}

// InstanceCredentialsConnectionType defines model for InstanceCredentials.ConnectionType.
type InstanceCredentialsConnectionType string

// SessionCredential A session credential and the identity it speaks for.
type SessionCredential struct {
	// ExpiresAt When it stops working regardless of use. A session outliving this
	// has to exchange again, which it cannot do -- so the window is
	// generous enough to cover a long console attach.
	ExpiresAt time.Time `json:"expiresAt"`

	// Identity Who a session is, as resolved from its token.
	Identity Identity `json:"identity"`

	// Token Present this as the bearer token on later calls. Hold it in
	// memory only: putting it in the environment would undo the reason
	// it exists.
	Token string `json:"token"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// IsLoginNameReservedParams defines parameters for IsLoginNameReserved.
type IsLoginNameReservedParams struct {
	Name string `form:"name" json:"name"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(w http.ResponseWriter, r *http.Request)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(w http.ResponseWriter, r *http.Request)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(w http.ResponseWriter, r *http.Request)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(w http.ResponseWriter, r *http.Request)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectSessionGuest operation middleware
func (siw *ServerInterfaceWrapper) ConnectSessionGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "guestId" -------------
	var guestID int64

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", r.PathValue("guestId"), &guestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectSessionGuest(w, r, guestID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeSessionToken operation middleware
func (siw *ServerInterfaceWrapper) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeSessionToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessionGuests operation middleware
func (siw *ServerInterfaceWrapper) ListSessionGuests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessionGuests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionIdentity operation middleware
func (siw *ServerInterfaceWrapper) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionIdentity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IsLoginNameReserved operation middleware
func (siw *ServerInterfaceWrapper) IsLoginNameReserved(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IsLoginNameReservedParams

	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IsLoginNameReserved(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicEndpoint(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSessionCredential operation middleware
func (siw *ServerInterfaceWrapper) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSessionCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/exchange", wrapper.ExchangeSessionToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/revoke", wrapper.RevokeSessionCredential)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/guests", wrapper.ListSessionGuests)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/session/connect/{guestId}", wrapper.ConnectSessionGuest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/login-name-reserved", wrapper.IsLoginNameReserved)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/public-endpoint", wrapper.GetPublicEndpoint)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/session/identity", wrapper.GetSessionIdentity)

	return m
}

type UnauthorizedJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type ConnectSessionGuestRequestObject struct {
	GuestID int64 `json:"guestId"`
}

type ConnectSessionGuestResponseObject interface {
	VisitConnectSessionGuestResponse(w http.ResponseWriter) error
}

type ConnectSessionGuest200JSONResponse ConnectInfo

func (response ConnectSessionGuest200JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ConnectSessionGuest401JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ConnectSessionGuest403JSONResponse Error

func (response ConnectSessionGuest403JSONResponse) VisitConnectSessionGuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionTokenRequestObject struct {
}

type ExchangeSessionTokenResponseObject interface {
	VisitExchangeSessionTokenResponse(w http.ResponseWriter) error
}

type ExchangeSessionToken200JSONResponse SessionCredential

func (response ExchangeSessionToken200JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeSessionToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExchangeSessionToken401JSONResponse) VisitExchangeSessionTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuestsRequestObject struct {
}

type ListSessionGuestsResponseObject interface {
	VisitListSessionGuestsResponse(w http.ResponseWriter) error
}

type ListSessionGuests200JSONResponse []Guest

func (response ListSessionGuests200JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessionGuests401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessionGuests401JSONResponse) VisitListSessionGuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentityRequestObject struct {
}

type GetSessionIdentityResponseObject interface {
	VisitGetSessionIdentityResponse(w http.ResponseWriter) error
}

type GetSessionIdentity200JSONResponse Identity

func (response GetSessionIdentity200JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionIdentity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSessionIdentity401JSONResponse) VisitGetSessionIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReservedRequestObject struct {
	Params IsLoginNameReservedParams
}

type IsLoginNameReservedResponseObject interface {
	VisitIsLoginNameReservedResponse(w http.ResponseWriter) error
}

type IsLoginNameReserved200JSONResponse struct {
	Reserved bool `json:"reserved"`
}

func (response IsLoginNameReserved200JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IsLoginNameReserved401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IsLoginNameReserved401JSONResponse) VisitIsLoginNameReservedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpointRequestObject struct {
}

type GetPublicEndpointResponseObject interface {
	VisitGetPublicEndpointResponse(w http.ResponseWriter) error
}

type GetPublicEndpoint200JSONResponse struct {
	Endpoint string `json:"endpoint"`
}

func (response GetPublicEndpoint200JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEndpoint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPublicEndpoint401JSONResponse) VisitGetPublicEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeSessionCredentialRequestObject struct {
}

type RevokeSessionCredentialResponseObject interface {
	VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error
}

type RevokeSessionCredential204Response struct {
}

func (response RevokeSessionCredential204Response) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeSessionCredential401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSessionCredential401JSONResponse) VisitRevokeSessionCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ConnectSessionGuest What it takes to open this guest's console.
	// (POST /session/connect/{guestId})
	ConnectSessionGuest(ctx context.Context, request ConnectSessionGuestRequestObject) (ConnectSessionGuestResponseObject, error)
	// ExchangeSessionToken Trade the minted token for a session credential.
	// (POST /session/exchange)
	ExchangeSessionToken(ctx context.Context, request ExchangeSessionTokenRequestObject) (ExchangeSessionTokenResponseObject, error)
	// ListSessionGuests The guests this session may reach.
	// (GET /session/guests)
	ListSessionGuests(ctx context.Context, request ListSessionGuestsRequestObject) (ListSessionGuestsResponseObject, error)
	// GetSessionIdentity Who the calling token belongs to.
	// (GET /session/identity)
	GetSessionIdentity(ctx context.Context, request GetSessionIdentityRequestObject) (GetSessionIdentityResponseObject, error)
	// IsLoginNameReserved Whether a login name means "browse" rather than "connect".
	// (GET /session/login-name-reserved)
	IsLoginNameReserved(ctx context.Context, request IsLoginNameReservedRequestObject) (IsLoginNameReservedResponseObject, error)
	// GetPublicEndpoint The hostname clients use to reach this proxpass.
	// (GET /session/public-endpoint)
	GetPublicEndpoint(ctx context.Context, request GetPublicEndpointRequestObject) (GetPublicEndpointResponseObject, error)
	// RevokeSessionCredential Give up this session's credential.
	// (POST /session/revoke)
	RevokeSessionCredential(ctx context.Context, request RevokeSessionCredentialRequestObject) (RevokeSessionCredentialResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectSessionGuest operation middleware
func (sh *strictHandler) ConnectSessionGuest(w http.ResponseWriter, r *http.Request, guestID int64) {
	var request ConnectSessionGuestRequestObject

	request.GuestID = guestID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectSessionGuest(ctx, request.(ConnectSessionGuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectSessionGuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectSessionGuestResponseObject); ok {
		if err := validResponse.VisitConnectSessionGuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeSessionToken operation middleware
func (sh *strictHandler) ExchangeSessionToken(w http.ResponseWriter, r *http.Request) {
	var request ExchangeSessionTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeSessionToken(ctx, request.(ExchangeSessionTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeSessionToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeSessionTokenResponseObject); ok {
		if err := validResponse.VisitExchangeSessionTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSessionGuests operation middleware
func (sh *strictHandler) ListSessionGuests(w http.ResponseWriter, r *http.Request) {
	var request ListSessionGuestsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessionGuests(ctx, request.(ListSessionGuestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessionGuests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionGuestsResponseObject); ok {
		if err := validResponse.VisitListSessionGuestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessionIdentity operation middleware
func (sh *strictHandler) GetSessionIdentity(w http.ResponseWriter, r *http.Request) {
	var request GetSessionIdentityRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessionIdentity(ctx, request.(GetSessionIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessionIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionIdentityResponseObject); ok {
		if err := validResponse.VisitGetSessionIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IsLoginNameReserved operation middleware
func (sh *strictHandler) IsLoginNameReserved(w http.ResponseWriter, r *http.Request, params IsLoginNameReservedParams) {
	var request IsLoginNameReservedRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IsLoginNameReserved(ctx, request.(IsLoginNameReservedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IsLoginNameReserved")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IsLoginNameReservedResponseObject); ok {
		if err := validResponse.VisitIsLoginNameReservedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicEndpoint operation middleware
func (sh *strictHandler) GetPublicEndpoint(w http.ResponseWriter, r *http.Request) {
	var request GetPublicEndpointRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicEndpoint(ctx, request.(GetPublicEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicEndpointResponseObject); ok {
		if err := validResponse.VisitGetPublicEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeSessionCredential operation middleware
func (sh *strictHandler) RevokeSessionCredential(w http.ResponseWriter, r *http.Request) {
	var request RevokeSessionCredentialRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSessionCredential(ctx, request.(RevokeSessionCredentialRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSessionCredential")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeSessionCredentialResponseObject); ok {
		if err := validResponse.VisitRevokeSessionCredentialResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFv7bxtJcv5XGpMDNlnwob1dJAfuL1F8hq1kYwuWjA2wY1jNmSKnjzPVs909oniG//egqrrnwYfl3Pny",
	"m0jOo7vqq6++qmp9ygrbtBYBg89WnzIHvrXogT+8R92FyjrzVyjpc2ExAAb6U7dtbQodjMXlX7xF+s4X",
	"FTSa/vqDg022yv5pOTx8Kb/65UvnrMs+f/48y0rwhTMtPSRbZfcVqGB3gMp41RjvDW5nCp5a46CcKV07",
	"0OVBdZ4+Wac63KHd4yKjR8Wn08tfWEQowg1uLH2cvuTlI7hDqAxuFQKUUKpglW0BlUVQ2w58+M6rwqK3",
	"NcyUxlKhlev12nZBaTzk9A04uZpWYtAHjQUscsxmWetsCy4YsSFf9JxNXvFFn2dZetJzN9zE6144KAGD",
	"0bVnMzj4vSNzZavf4ptHz/wwy8KhhWyV2fVfoOAXijdWn45WDenrqfWula+sC8qB9hYX6s9QmzU4HaA+",
	"kJ1UCUGbGsqVChV4UD2clHaQowNdVHpdg1rDxjpQWhW6rsGRywlrtJdCByjFlHG5PjiD25MNyiLP7epV",
	"Mvrx8sVl2iutWlPswDEKvDLhaDOFds6A750fKh1UYbu6zHENDEJCDm+I9ipPXimtPHhvLKrK1qVXoTJe",
	"1cYHtSGgBK/2la0hx9psIr4aSyjaKBPICgiP4AiAhGF+yTlUmfJ0dxQ/zu6VKWf9+rTf8Yt1eqKxuMhm",
	"2ca6RodslRkM//rTYGmDAbbgxlC84Vf9H254oxs4Xd0NFnVH8ebt4PVCIyFqL3bQoaiURTLE3oSKo015",
	"KCyWBJ3fycILdcNmIpNbrA9qGpt9KB45eJbjvjJFRbfuK7oLHLC5rQIsW2swiI/JV75/jD+Lw1mGcY8n",
	"P7TOPjX26eaCfxLBmJK3aJAhcSs39W+dKVhsF+qHq6vFWUv7oEMncYpdQ6HgOkRaAf1m2xbKUVgMi5Mv",
	"hrsKoofH5sy1R5FmyizuOV7Zr2G84wlmjvBwLkpvmLrC4dRUv1Z2FEnGzyhkHXhbP0KpNs42bDfOFouT",
	"4ChqAxguuUB+/c7HWFmo67UHlPgkVOmyMWh8cDpY95WxUhrf1vpwHvn8Uosbs+0clMrEXVN4MvbppZ0H",
	"txpez58VGZwyXY5hvG67R/5poejJtd0a+cwcikrXRkt8SJDlWFTWw4wCL1KMDWpPWKeL3t/QKrq6VHET",
	"FxBv/DWtbAT6tbU1aKQfabnnNz5aHr0tuZTYlVxJQTBTO2hH9u9KE+i+xbMJgF87tf6w0LOIO5M2zy47",
	"RWQxXNgvsKeYyvpA5NMrh0WOOd4T40eGanQAZ3Q9AnPT+cAeWIPiTChZJKI6VJBjqYNea3JZpZEo01JK",
	"EBonUVTDiM3Jp5X2ag2AapBrOQarGr07q0l0a+4pdCRETlydfr6DwsGZNHrrgCNmXwFOLRKX5WXF9NP1",
	"7c3iHJx0a967+uzrh73dH/FVANcQ3RyIf3x1luPM16arixSOtrwQxT0DJXiIGqIbJCLP7dT76rUVNXLu",
	"t/+CM/x3+/K/54CFJee3zjzqAGoHh5kyWBuEhbrGidETt1A4KZ3jDg7q9vr+NeGwXzSnvPWB0SaSBtTG",
	"kMpdQ6E7D4K+BNRCI9ogpETPM16VY4Vku+BNCUzELIMuEIf31a114/2PM5mv3kfu+PoMFLFzgpTounOB",
	"fyebGuL+rLZNO++vYl3CCE+kbYLyLegd08G52JJ6xV+Hc1kNOFwpRXu1t25HbnCw1a6swXsSgZ0n7/ZL",
	"sV2ozaN4y/gcKdKDVfBUVBq3oPRWG5ypqG1CdJoqrZrPifBp7XuDJaU6n+MWEJztvAK03baiRxUcqlrV",
	"Frep7lE6hN6hfSiVOsA8mEEETMNuyOVfLFzSdSRHiGQu0wtL55jK1qAdMQqXhxZVTcTKCc4v1Gtbl5za",
	"MMcGGusOLA1Xqu0CEzT/xs8BfDTOYsP0xVmvw1LMJDVNjiYoeCIR+DUliGxhNvL6yBSnQCTEQ9E5Ew53",
	"ZBCBTHT2/XlzXMddNxQ2JQXwA3Fgq70f8f18Bwf/0OcoCliSszlOqiopOGJWCXaSkklA241aaywX6o6I",
	"bV5zjtYkvyXvzAmelOQmtdKbt/eqBEnonMU0HlLVNDy/sBicrf1qQjNRzzz84e7u9cf3dy/ffbx+f//6",
	"gYmJKMfuUZag9s4EKR0PU6IiFTCLZUWtTaMod5axkOCSjXLtxrptKisZjCxhGFaDl6sQWmlNmLPdA1E0",
	"tl3rYkepTUqGwR8e3CM8KHhqrefaIcoBecoaBMzff5+Wfn178/33KxFjevIc/v2B9ibFCOgyR7vhVkWy",
	"bNIJRMFQb8a84Trk2NGoOqQMYmrYQqk6E/3ZyxAqU4cn6aIA7ycZYfiRPKgNDvXK9e0N6QxCp2et4NlT",
	"fWa6u3s9Tl+eSGlQQlJSaxT5Y0KO9CHoHQzyoag7H8BFS4LyJCTZyk7p2lv5W8z65u5OlcZBEYgB/vlh",
	"ScDwDzMlfy0peywXi8VDjrTKjTOApf8XjpmH2qzR+48EgIW3iz8+kLq2ZBEH07wnaBd/ljlSVmVIG6f+",
	"8+7tG+Ur3TJ0N+ZJ4pUWlx6u9sYxGBsdKBoVPAVwqOsciXy7BpzqYVBa6UCk2JlFSjdOEWC98kEfOJzn",
	"FB2B0gsxGMojl7o1S75wsbWk1hykPgZSfUM1L4HTFh0RIpQK4SlEXmgWOb6idKFDxFsTGdMZv1Pe1ICh",
	"JjWBuuESXG0M1BKraweakxs8gjvkyFXAjC2NVq0BYWNELV8P9CSlntJTsv8a2uur+wR7Z1lgc4tpzEFC",
	"7CmrO7lgh3bvYwrdweGIMqXKmooiXpQiPV5TGrKkyJi9Y5vLT9lTDeT5s/KFFXgkxhQ0z1lLpRqg1xtS",
	"+okl9prqCt8Ry1o3i52iU8KNvRVP6I6Bo0OyY99g9S3lQNM0UBoG9owY8+H27d29WsbtLpPOeGDf5ajP",
	"aSRpm2g2rBcdEbN2vFhMGPZWlWazYYPl2HaOSFJ+i4ujQkoqQ58S9pAmRql7FsHMvdjW2SKKp5AYgmhu",
	"xCzMO1gKGmOBnDbiK+3A06tzpNtEN0mhPPhN3Mgmi32b1JninAmsMtg3vKEcR/YxQa27A9eEFQWIQRVV",
	"SsrWtdlAWn/aDrO0uDjFdkzYYw1DDyCz+h1zQ5L2JqgGNPr0BTGe9Kzj47/zaQ1O8/eh0tKLeljSJcu8",
	"u7r6sWhNyX/AMr70YaHeSteNE7AYAIGNvabFs3SDUjlogcKHcDXqvOkwSgDcmVvluHZ275lCsOwrW/ro",
	"yP+P4HQtUm/GZEjhJtLMhJqyds8LifgoMWWz7BGcl7z9w+JqcUWSk9Knbk22yn5cXC1+JPWuQ8UqbFmB",
	"rkP1V27anyt730+JYRWdEdxB2oetrevY8I3U44N2vBPvqzI2YHoNr9HvwfWNcDzE2IziU90E5eARdN03",
	"oWXXVGwwWVL1nr2C8JrXnc2ms5s/Xl0djWwCPIVlW2tzNKyBJ920bEi7OyN4z85pYgo2XnXtYqJrs9Vv",
	"H2aZ75pGu0O2yn4xj4AE6NbZtVTIeutJO4u9sw90d8840f3LT9xQuSk/82zCnuvmv4PQORSmudSvefvm",
	"pbRmZkpvuGSooNilhj6xq/GJMBt9iP18E4SW+GKeRukSuH6ejel6xuQrFO2DHTf3VpETUoeHG2A6jh9i",
	"C64Fx1MukkI2zkaUOW0icZt72qR2cetRdYmsN8P3dIus66RZxWJEN1DGltVINA4pkWcXYxITa3L8CjWO",
	"wjTY2YRFEqvFQcdYwl0ja0KqTkZdCxnH6FBJu0JL0pS9kE1jz+P+tDshV7NJuGCYz1M7jGRG5w0jb+qK",
	"+TxHpkp6fLIIv32faoXOA9fjwYo/TqIujhhjV+FVHLS12ukGAjiC95e6/2lKo73aUniwuulDgK/yDwtu",
	"oRO9aY5u6VdlMS6ycR0aXAezUUQ/2/36/OFZtvjbB7zj+esF+ohjuNhcOYaZGQ1gFsTaP139cOml/S6W",
	"k2E13/Tj/8/MekQfEZI8EjQ+RdikWO41ivB/jtrH1q4YhcHcC39OBisVoK57Fa5b7VL3gjAcWaxnCIOU",
	"XdRe84gBkGoKqsCm9ZSQdk/Tv8bQpvLL9zPxYRfDUHxM4RGyRxyeVONl6n4hpU5UiYPKkgz4hf5G26VW",
	"zriDMFZEA3UQq0xk6kTGU5DnmLjKQZrBeiWT2WC3wJzGPdXjHuAaSOd6mc7mOOod6l4EWJ7k6SAyoGtn",
	"CfAozYgQZwSsfWMdvVAvtLiafLE3BQzvZ9SIhTbaSCNFh17R58j69BxdvYwOuRs3mv6BDHDabb0QOgj7",
	"427rvkrqe2Pd3xr9E2jfO8reg6mTDWWeclLPPI9vIeiLOvE6HlTZGKoOk1CMiqmEwpTgh0pP2INHwgIv",
	"0olUaSU6uEAwUUTEMimKSZLXdR2zMfECy3KCU218gJRYN3w8gHuoInQmM0/lAXyq3Ie51ov+RMSYsBdq",
	"dKImDdWjzp+csCCJUzq9V5rX8nMvJqaMo/sedGGbaKccj8rSE5H4MBuGcGwEFUwD50LhF+Mnadv/vXFg",
	"AjT+q8/3xESsndOHS0ExHJIRoH2bIEhZN5JTP45Movd52I9b/GeBfz8AcXCe6hsYUr09268YuFT7XVxt",
	"7IASQ3MA0a1RKUC9WQ2iL8fgOh/21oXqkFLgDu1+6O9Mzxn1gptReI4PZNnH9BHJl1CXmik5koy72ECR",
	"BaRTbG5UvCTDUiwSj3OjQLqEw1EZfp2cKdInnKmRT0MoB3NWxPvK8iCDYjGepKk0j5F41D4wxoWSMkZI",
	"P6z5B+aKYSD0JXU14sdvEg6/VrbHntQwlBJGWf3ZaOCW5pxE+dwBk3v55cAYU+x3PlaEfVNqVA7JQY94",
	"gZyak+dzB+HBe0KRKeDfqaR7YNoUHEW+HQVLbe0uxsqQUtiipcozfkqeiYLxu9iAk/cmDlUW1aRV1x9v",
	"o6otgnkNQCrU1mVfXlJJs68s96+I9CjQZEjDuBvObPVhVIPe+RzTgbv5XJp8fPBnXKrxYbqofqGuk/3E",
	"aAx8qD1MZnhTfN/4X8h3b3QD75LnToo3rrx+78AdhtIrjp8v113HrZO/t8qaTpbHMDs+gnM0luwvPTOC",
	"PBtlj+BKU4RvFFsinPX48I+0I/OMe32QZ5OOQZ4m+Xn2fOC13bo2xTyVOxeD7q6ye0z6KIkKObWm1tot",
	"Tsd2DgrrSoZqGoDl6H1VcpU+zg5abRz4atqT9va4xkgdihxv3739n9vru7uPt+//45ebFx9fvvnz7dub",
	"N/dpdEch+LJpw2E4VFNCW9sD1zSS24Kc8eEwi+JpXPX5n1nw9e0ljYoPyPZlB+1aedO09YEPnvGGKusC",
	"OFXrNdQXksEtG/xlsvc3xfTYi88c9k1Xfi2k0w0z1Vrvzbo+KCALfzM5RfTL2Bbu8Uoq2HEDICHseVQ7",
	"eLS7L1XMQtqMjgGHJJl64I1EwfSECRNsQYlkFHMJP0+tcYdpF1AHVZLST9KhT5KsTmrQEgzHI6B4BkIG",
	"7zy5Pweod7zR0wrxBFY/XThJORqseLW1yEckeTgm0xLuYn4TJ78yj6C6diKYv/PPl4rTbvjx+Y7fPlBe",
	"kHLwXKPwl3S+wGJ9iGc8qXhD6bfLJte2QzngrZzt5FyELkvHw3s5sEG8JaWeV611fMByr13J/1URIcOt",
	"5aHeEK0Vh5hxUgRDmjfIQ8rIp0EbTAKyc3U8PbFaLn/4478trhZXix9Wf7r601VGu41GOj0QxTqDZcm8",
	"p+jxdGgm89JSWrFjEdhn5WT4z7NP6as4Wfj84fP/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
